version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
     - data-volume:/var/lib/mysql
    ports:
     - "3306:3306"
  bench:
    build: .
    links:
     - "mysql:mysql"
     
volumes:
  data-volume:
